In [1]:
import numpy as np

### Basic Concept

In [3]:
np.zeros((3, 4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [3]:
np.zeros((3, 4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [10]:
np.random.rand(2, 3)

array([[ 0.14449985,  0.85683145,  0.12433783],
       [ 0.227618  ,  0.57664536,  0.93469513]])

In [11]:
np.random.rand(2, 3, 4)

array([[[ 0.36439364,  0.93385903,  0.19897749,  0.26851868],
        [ 0.90027214,  0.37798904,  0.55714265,  0.31611295],
        [ 0.58798434,  0.29562904,  0.07918637,  0.15085628]],

       [[ 0.94814728,  0.37945728,  0.04277226,  0.61138138],
        [ 0.30669814,  0.26550849,  0.97868626,  0.27489412],
        [ 0.85653903,  0.35125621,  0.30487337,  0.08567811]]])

In [12]:
np.random.rand(2, 3, 4, 5)

array([[[[ 0.20316719,  0.15161801,  0.10407042,  0.77451752,  0.93672331],
         [ 0.76444187,  0.97828459,  0.82401017,  0.82181309,  0.32086421],
         [ 0.05950052,  0.73593578,  0.11755223,  0.51796456,  0.2891094 ],
         [ 0.62723661,  0.62516616,  0.42282745,  0.64517623,  0.06338011]],

        [[ 0.02922349,  0.28396023,  0.5854269 ,  0.58897748,  0.52437444],
         [ 0.56845126,  0.27719333,  0.09936534,  0.56771305,  0.09507327],
         [ 0.70059952,  0.11320325,  0.5026039 ,  0.6766999 ,  0.04461843],
         [ 0.38113212,  0.3346442 ,  0.62878296,  0.02732795,  0.10485513]],

        [[ 0.24264663,  0.44610288,  0.04595799,  0.46612985,  0.59127972],
         [ 0.05347743,  0.71744432,  0.02693087,  0.97047923,  0.84736652],
         [ 0.31316435,  0.13159242,  0.87344611,  0.7715103 ,  0.73513916],
         [ 0.41865313,  0.56456487,  0.37608361,  0.36753867,  0.80156979]]],


       [[[ 0.2720617 ,  0.56365899,  0.25571902,  0.12646368,  0.92831072],
    

In [16]:
np.zeros((3, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [14]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

### Common Operation

In [18]:
# reshape
x = np.arange(12)

In [19]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
x.shape

(12,)

In [21]:
x = x.reshape(1, 12)

In [22]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [23]:
x = x.reshape(3, 4)

In [24]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
# transpose
x = np.arange(5)

In [26]:
x

array([0, 1, 2, 3, 4])

In [27]:
x = x.reshape(1, -1)

In [28]:
x

array([[0, 1, 2, 3, 4]])

In [29]:
x.T

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [30]:
A = np.arange(12).reshape(3, 4)

In [31]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
A.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [33]:
B = np.arange(24).reshape(2, 3, 4)

In [34]:
B

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [35]:
B.transpose(1, 0, 2)

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [36]:
B

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [37]:
B.transpose(2, 1, 0)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [38]:
B.shape

(2, 3, 4)

In [39]:
B2 = B.transpose(2, 1, 0)

In [40]:
B2

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [41]:
B2.shape

(4, 3, 2)

### Matrix Multiply

In [42]:
A = np.arange(6).reshape(3, 2)

In [43]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [44]:
B = np.arange(6).reshape(2, 3)

In [45]:
B

array([[0, 1, 2],
       [3, 4, 5]])

In [46]:
np.matmul(A, B)

array([[ 3,  4,  5],
       [ 9, 14, 19],
       [15, 24, 33]])

In [48]:
np.matmul(B, A)

array([[10, 13],
       [28, 40]])

### Element-wise Operation

In [49]:
A = np.arange(6).reshape(3, 2)

In [50]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [51]:
A * A

array([[ 0,  1],
       [ 4,  9],
       [16, 25]])

In [52]:
A^2

array([[2, 3],
       [0, 1],
       [6, 7]], dtype=int32)

In [53]:
A**2

array([[ 0,  1],
       [ 4,  9],
       [16, 25]], dtype=int32)

In [54]:
A - A

array([[0, 0],
       [0, 0],
       [0, 0]])

In [55]:
A + A

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [60]:
A % A

c:\users\hepingtao\appdata\local\programs\python\python35\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in remainder
  """Entry point for launching an IPython kernel.


array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [61]:
# 逆矩阵
A = np.arange(4).reshape(2, 2)

In [62]:
A

array([[0, 1],
       [2, 3]])

In [63]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [64]:
A_ = np.linalg.inv(A)

In [65]:
A_

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [66]:
A * A_

array([[-0. ,  0.5],
       [ 2. ,  0. ]])

In [67]:
np.matmul(A, A_)

array([[ 1.,  0.],
       [ 0.,  1.]])

%%latex
$$c = \sqrt{a^2 + b^2}$$

In [71]:
%%bash
ls -ltr

total 24
-rw-r--r-- 1 hepingtao 1049089 22695 Oct 23 18:18 basics.ipynb
